---
kind: Template
apiVersion: v1
metadata:
  name: beego-example
labels:
  template: beego-example
  app: beego-example
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: beego-example
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: beego-example  
- kind: Route
  apiVersion: v1
  metadata:
    name: beego-example
  spec:
    host: "${APPLICATION_DOMAIN}"
    to:
      kind: Service
      name: beego-example
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: beego-example
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: beego-example
  spec:
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      contextDir: "${CONTEXT_DIR}"
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: beego-example:latest
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: "${GITHUB_WEBHOOK_SECRET}"
    postCommit:
      script: go test -v ./...
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: beego-example
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - beego-example
        from:
          kind: ImageStreamTag
          name: beego-example:latest
    - type: ConfigChange
    replicas: 1
    selector:
      name: beego-example
    template:
      metadata:
        name: beego-example
        labels:
          name: beego-example
      spec:
        containers:
        - resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          name: beego-example
          image: beego-example
          ports:
          - containerPort: 8080
- kind: HorizontalPodAutoscaler
  apiVersion: autoscaling/v1
  metadata:
    name: beego-example
  spec:
    maxReplicas: 10
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps.openshift.io/v1
      kind: DeploymentConfig
      name: beego-example
    targetCPUUtilizationPercentage: 50
parameters:
- name: SOURCE_REPOSITORY_URL
  value: https://github.com/tuanbo91/golang-ex.git
- name: SOURCE_REPOSITORY_REF
  value: master
- name: CONTEXT_DIR
- name: APPLICATION_DOMAIN
  value: chat.leanhtuan.org
- name: GITHUB_WEBHOOK_SECRET
  generate: expression
  from: "[a-zA-Z0-9]{40}"